### ISSUE TITLE
Clearer X-Axis description of histogram and flamegraph panel

### ISSUE THREAD

**Issue by simonswine** [grafana/phlare#271]
I think we should make it clearer what the X-axis represents in the histogram and the flame graph represent:

While the histogram's x-axis is time, the flamegraph's x-axis unit is the is the percentage of the resource used.

I wonder if we need to do something before the obscon mile stone, wdyt? 

For reference on the top the histogram and at the bottom the flamegraph as of right now:

![scrn-2022-09-30-11-55-12](https://user-images.githubusercontent.com/223048/193255315-3e9a80c6-7470-4f1e-b1e8-59723d52f7ed.png)

**Comment by joey-grafana** [comment]
Closing this as completed. Summary: we added the unit values to each block in [this pr](https://github.com/grafana/grafana/pull/57959), and explored adding a scale above the flame graph in [this pr](https://github.com/grafana/grafana/pull/57529), but ultimately didn't go with the scale as it seemed like adding the unit values to each block was enough.
