### ISSUE TITLE
Artifacts report incorrect version number

### ISSUE THREAD

**Issue by attachmentgenie** [grafana/phlare#391]
#### Describe the bug
while starting the official docker container and the downloadable artifact (darwin amd64) the version does not report 0.1.0 but shows the git hash.

`evel=info caller=phlare.go:301 ts=2022-11-02T21:25:16.174611565Z msg="Phlare started" version="(version=main-8cdca06f, branch=main, revision=8cdca06f)"`

#### To Reproduce

./phlare 

#### Expected behavior

the version to be reported as 0.1.0

#### Environment

- Infrastructure: docker
- Deployment tool: bash/docker

**Comment by cyriltovena** [comment]
Thanks for the report I'll look into it.
