### ISSUE TITLE
Jsonnet values override does not work

### ISSUE THREAD

**Issue by glindstedt** [grafana/phlare#397]
#### Describe the bug

I'm either missing something obvious or the jsonnet template values override does not seem to be working.

#### To Reproduce

I'm trying to deploy phlare in microservices mode, currently I have a file like this:

```jsonnet
local phlare = import 'phlare/jsonnet/phlare/phlare.libsonnet';
local valuesMicroServices = import 'phlare/jsonnet/values-micro-services.json';
local values = import 'phlare/jsonnet/values.json';

phlare.new(overrides=valuesMicroServices {
  namespace: 'phlare',
  phlare+: {
    nameOverride: 'foobar',
  },
})
```

But anything I provide to the `overrides` argument doesn't seem to have any effect, and it's still getting deployed in monolithic mode.

#### Expected behavior

That I can override the default phlare configurations.

#### Environment

- Infrastructure: kubernetes
- Deployment tool: jsonnet

#### Additional Context

Relates to https://github.com/grafana/phlare/issues/355

**Comment by simonswine** [comment]
Thanks for reporting this, it just highlights how important grafana/pyroscope#2091 is. I will provide a PR with an initial example soonish.

But to achieve what you are after,  you need to move the values into the overrides struct like this:

```jsonnet
local phlare = import 'phlare/jsonnet/phlare/phlare.libsonnet';
local valuesMicroServices = import 'phlare/jsonnet/values-micro-services.json';
local values = import 'phlare/jsonnet/values.json';

phlare.new(name='foobar', overrides={
  namespace: 'phlare',
  values+: valuesMicroServices {
    phlare+: {
      nameOverride: 'foobar',
    },
  },
})
```

**Comment by glindstedt** [comment]
Ah thanks! I actually just figured that out myself. Closing this issue :+1:
