### ISSUE TITLE
Possible to POST PPROF to Phlare

### ISSUE THREAD

**Issue by mikkeschiren** [grafana/phlare#402]
#### POST PPROF to phlare

While support for PHP is hopefully one of the next steps for the agent while trying phlare out on languages not yet supported, could we POST direct to Phlare dumps in PPROF format? And if so - how would it best be done?

**Comment by simonswine** [comment]
I do realize that this is quite horrible from a usability point of view.

**Comment by simonswine** [comment]
I do realize this is quite horrible from a usability point of view, but you can use the HTTP interface provided by the [connect API](https://github.com/bufbuild/connect-go). 

This is all poorly documented and quite a bit subject to change, but using this CLI snippet you should be able to upload your pprofs to Phlare.

```
$ curl -v -H "Content-Type: application/json" -d '{"series":[{"labels":[{"name":"__name__","value":"profile_cpu"},{"name":"job","value":"manual"}], "samples": [{"raw_profile": "'$(cat profile |base64 -w 0)'"}]}]}' http://localhost:4100/push.v1.PusherService/Push 
```

PR are more than welcome to add this functionality to profilecli: grafana/pyroscope#2088

**Comment by mikkeschiren** [comment]
Great, thanks for the answer and the example.
