### ISSUE TITLE
Unable to set scrape timeout higher than scrape interval

### ISSUE THREAD

**Issue by eric-engberg** [grafana/phlare#463]
#### Describe the bug
When attempting to set scrape interval to 10s and timeout to 30s the following error is given.
`failed creating phlare: scrape timeout must be larger or equal to inverval for: java`
when using
```
- job_name: "java"
  scrape_interval: "10s"
  scrape_timeout: "30s"
```

#### To Reproduce

1. Set timeout to a higher value than interval
2. Start phlare

#### Expected behavior

A higher timeout than interval should be accepted and work.

#### Environment

- Infrastructure: EKS
- Deployment tool: ArgoCD, Kustomize, Helm

**Comment by cyriltovena** [comment]
I'll send a fix for that bug soon.

**Comment by cyriltovena** [comment]
related to https://github.com/parca-dev/parca/pull/2220/files
