### ISSUE TITLE
It doesn't appear that `config.expand-env` is registered

### ISSUE THREAD

**Issue by dmolik** [grafana/phlare#470]
#### Describe the bug
command line flag config.expand-env doesn't appear to be registered

#### To Reproduce

1. Start Phlare (v0.1.1) and origin/HEAD
2. run with ./phlare -config.expand-env=true

#### Expected behavior

it bombs out. 

#### Environment

All

**Comment by cyriltovena** [comment]
We don't yet support config expansion but we should so let's keep the issue, the code could be taken from Loki.

**Comment by dmolik** [comment]
there is reference to config expansion, in the documentation, you may want to comment it out in the mean time. https://grafana.com/docs/phlare/v0.1.x/operators-guide/configure/reference-configuration-parameters/#use-environment-variables-in-the-configuration
