### ISSUE TITLE
Integration for Nodejs seems to work, but "Select Profile type" dropdown seems buggy

### ISSUE THREAD

**Issue by rjdp** [grafana/phlare#498]
#### Describe the bug

Integration for Nodejs seems to work, but "Select Profile type" dropdown seems buggy. ie it shows `samples` twice under the "cpu_process" profile type and show `inuse_objects` and `inuse_space` twice under memory profile type dropdown in the Grafana UI

#### To Reproduce

1. Use the docker-compose from `tools/` dir in the repo
2. Add a sample express app and use Pyroscope client's express middleware to add `pprof` endpoints
3. Add a target for express nodejs app in `phlare` config

#### Expected behavior

Should not duplicate options under selected profile type in grafana UI

#### Environment

- Infrastructure: [laptop]
- Deployment tool: [docker-compose] ( from [docker-compose ](https://github.com/grafana/phlare/tree/main/tools/docker-compose)directory in repo )

#### Screenshots

<img width="1449" alt="Screenshot 2023-02-05 at 8 18 21 AM" src="https://user-images.githubusercontent.com/7734938/216799294-9c9d65ba-d9fa-43df-a02d-e23d36da9927.png">
<img width="1494" alt="Screenshot 2023-02-05 at 8 18 29 AM" src="https://user-images.githubusercontent.com/7734938/216799298-04adebcb-d320-4b6c-b324-3bfc29a1a9c0.png">

#### Additional Context

```javascript
const express = require('express')
const app = express()
const port = 3002

const Pyroscope= require('@pyroscope/nodejs');

Pyroscope.init({ tags: { region: 'us-east-1' } })

app.use(Pyroscope.expressMiddleware())

app.get('/', (req, res) => {
  res.send('Hello World!')
})


app.get('/primes', (req, res) => {
    let to = req.query.to ? Number(req.query.to) : 100;
    res.send(prime_number_from_1_to(to))
  })

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})


function divisible(i, j){
    return i % j == 0
}
function prime_number_from_1_to(to=100){
    let prime_numbers = []
    for (let i=1; i<to; i++) {
        if (i > 1) {
            let not_div = true;
            for (let j=2; j<i; j++) {
                if (divisible(i, j)){
                    not_div = false;
                    break;
                }      
            }
            if (not_div) {
                prime_numbers.push(i)
            } 
        }   
    }
    return prime_numbers
}
```

**Comment by cyriltovena** [comment]
Seems that we have some incompatibilities with the type provided by Pyroscope. 

Can you check what is being sent back from the `ProfileType` API call when opening the Phlare data source in the web browser ?

**Comment by cyriltovena** [comment]
There's an API call made once you land on explore to fetch the profile types, it has more info and can tell us why it's a duplicate.

**Comment by rjdp** [comment]
I got following reponse from `http://localhost:3000/api/datasources/1/resources/profileTypes` :

```json
[
   {
      "ID":"block:contentions:count:contentions:count",
      "name":"block",
      "sample_type":"contentions",
      "sample_unit":"count",
      "period_type":"contentions",
      "period_unit":"count"
   },
   {
      "ID":"block:delay:nanoseconds:contentions:count",
      "name":"block",
      "sample_type":"delay",
      "sample_unit":"nanoseconds",
      "period_type":"contentions",
      "period_unit":"count"
   },
   {
      "ID":"goroutine:goroutine:count:goroutine:count",
      "name":"goroutine",
      "sample_type":"goroutine",
      "sample_unit":"count",
      "period_type":"goroutine",
      "period_unit":"count"
   },
   {
      "ID":"memory:alloc_objects:count:space:bytes",
      "name":"memory",
      "sample_type":"alloc_objects",
      "sample_unit":"count",
      "period_type":"space",
      "period_unit":"bytes"
   },
   {
      "ID":"memory:alloc_space:bytes:space:bytes",
      "name":"memory",
      "sample_type":"alloc_space",
      "sample_unit":"bytes",
      "period_type":"space",
      "period_unit":"bytes"
   },
   {
      "ID":"memory:inuse_objects:count:inuse_space:bytes",
      "name":"memory",
      "sample_type":"inuse_objects",
      "sample_unit":"count",
      "period_type":"inuse_space",
      "period_unit":"bytes"
   },
   {
      "ID":"memory:inuse_objects:count:space:bytes",
      "name":"memory",
      "sample_type":"inuse_objects",
      "sample_unit":"count",
      "period_type":"space",
      "period_unit":"bytes"
   },
   {
      "ID":"memory:inuse_space:bytes:inuse_space:bytes",
      "name":"memory",
      "sample_type":"inuse_space",
      "sample_unit":"bytes",
      "period_type":"inuse_space",
      "period_unit":"bytes"
   },
   {
      "ID":"memory:inuse_space:bytes:space:bytes",
      "name":"memory",
      "sample_type":"inuse_space",
      "sample_unit":"bytes",
      "period_type":"space",
      "period_unit":"bytes"
   },
   {
      "ID":"process_cpu:cpu:nanoseconds:cpu:nanoseconds",
      "name":"process_cpu",
      "sample_type":"cpu",
      "sample_unit":"nanoseconds",
      "period_type":"cpu",
      "period_unit":"nanoseconds"
   },
   {
      "ID":"process_cpu:samples:count:cpu:nanoseconds",
      "name":"process_cpu",
      "sample_type":"samples",
      "sample_unit":"count",
      "period_type":"cpu",
      "period_unit":"nanoseconds"
   },
   {
      "ID":"process_cpu:samples:count:wall:microseconds",
      "name":"process_cpu",
      "sample_type":"samples",
      "sample_unit":"count",
      "period_type":"wall",
      "period_unit":"microseconds"
   },
   {
      "ID":"process_cpu:wall:microseconds:wall:microseconds",
      "name":"process_cpu",
      "sample_type":"wall",
      "sample_unit":"microseconds",
      "period_type":"wall",
      "period_unit":"microseconds"
   }
]
```

**Comment by rjdp** [comment]
@cyriltovena I think theres something wrong the way I am sampling my `/debug/pprof/profile?seconds=9` are too slow (takes more than 10 sec) a lot of times phlare errors while scraping.  I verified this happens for python app provided in examples.

Do you have some recommendation for sampling rate , is it normal for profiling endpoints to be this slow, I faced this primarily for python and nodejs , as far as I can remember these endpoint were snappy on golang/rust example app ?

**Comment by rjdp** [comment]
Here I used Pyroscope client and its Defaults are being used ,

https://github.com/pyroscope-io/pyroscope-nodejs#configuration 

https://github.com/pyroscope-io/pyroscope-nodejs/blob/main/src/index.ts#L26

**Comment by rjdp** [comment]
I found that the Python pprof [integration]( https://pypi.org/project/pyroscope-io) for Pyroscope leverages [Py-spy
](https://github.com/benfred/py-spy). written in rust but its a push client, Does phlare support push clients ?

**Comment by cyriltovena** [comment]
>cyriltovena I think theres something wrong the way I am sampling my /debug/pprof/profile?seconds=9 are too slow (takes more than 10 sec) a lot of times phlare errors while scraping. I verified this happens for python app provided in examples.

Yes  `/debug/pprof/profile?seconds=9` should only take 9~10sec. Unclear why this is happening for you, have you tried increasing the scrape timeout ? As you suggested below may be the default sampling is too aggressive 100hz (100 samples per seconds) sounds like a good default.

> Here I used Pyroscope client and its Defaults are being used ,
> 
> https://github.com/pyroscope-io/pyroscope-nodejs#configuration
> 
> https://github.com/pyroscope-io/pyroscope-nodejs/blob/main/src/index.ts#L26

Those are good defaults yes !.

>I found out that the Python pprof [integration](https://pypi.org/project/pyroscope-io) for Pyroscope leverages [Py-spy](https://github.com/benfred/py-spy)
which seems to be very performant. written in rust but its a push client, Does phlare support push clients ?

Yes Phlare does but we yet still have to build those push SDK for each language. But we're going to invest there soon.

**Comment by rjdp** [comment]
Thanks @cyriltovena !!
