### ISSUE TITLE
Is there a way to push profiles to Phlare ?

### ISSUE THREAD

**Issue by rjdp** [grafana/phlare#507]
#### Describe the bug
Not a Bug, a question that I wanted clarification on

**Comment by wilfriedroset** [comment]
I reckon this is (or will be) doable with grafana agent.
See: https://grafana.com/docs/agent/latest/flow/reference/components/phlare.write/

**Comment by wilfriedroset** [comment]
Here is the post announcing the feature in grafana agent. 

https://grafana.com/blog/2023/02/01/grafana-agent-v0.31-release-new-helm-chart-flow-support-for-grafana-phlare-and-more/

**Comment by rjdp** [comment]
Thanks @wilfriedroset.
