### ISSUE TITLE
Log Queries Parameters

### ISSUE THREAD

**Issue by cyriltovena** [grafana/phlare#641]
Currently our logs doesn't contains body data from requests this means we can't see what parameters where used.

Would be nice to either improve or add a log with more information. The latter might be easier.

<img width="2168" alt="image" src="https://user-images.githubusercontent.com/1053421/233380364-96ccd04a-d394-4456-953d-518a2ecbd6e8.png">

**Comment by hi-rustin** [comment]
> Currently our logs doesn't contains body data from requests this means we can't see what parameters where used.
> 
> Would be nice to either improve or add a log with more information. The latter might be easier.

Did you mean we need to log it with middleware or log it in every handler?

**Comment by cyriltovena** [comment]
I don't mind. I suspect a connect-go middleware might help ? Not sure.

**Comment by hi-rustin** [comment]
> I suspect a connect-go middleware might help.

I will try this approach.
