### ISSUE TITLE
[frontend] add linting

### ISSUE THREAD

**Issue by eh-am** [grafana/phlare#672]
Would be nice to have linting rules for the frontend. We could reuse most of the ones from `@grafana/eslint-config`:
```
 {
  "extends": ["@grafana/eslint-config"]
}
```

Additional ones that would be useful:
* Forcing all imports to be absolute (using alias), this is so that they can be easily overridden downstream.
* Force React to have been imported (i think `@grafana/eslint-config` already has that, but worth mentioning)

**Comment by hi-rustin** [comment]
Thanks for writing this out! I am working on this.
