### ISSUE TITLE
Loss of data on restart

### ISSUE THREAD

**Issue by kolesnikovae** [grafana/phlare#688]
A restart may result in losing the head block:
![image](https://github.com/grafana/phlare/assets/12090599/41413187-f2bc-4c62-b4bb-c0112700937d)

Log from one of the ingesters (cluster of 4 ingesters with the default replication factor): apparently, shutdown didn’t finish gracefully:
![image](https://github.com/grafana/phlare/assets/12090599/2838bd21-ccbf-44e5-ab5f-8c846efe294c)

I find it interesting that none of the ingesters has finished shutdown as well: no panics or explicit errors in the log – however, most likely this indicates a problem with log collection.

It seems that under some circumstances a block is not picked up after the restart, and the head is getting polluted with chunks:
```
/ $ ls -la /data/1218/head | wc -l
276
/ $ du -sh /data/1218/head
49.9G   /data/1218/head
```

**Comment by kolesnikovae** [comment]
Also see https://github.com/grafana/pyroscope/issues/2076

**Comment by cyriltovena** [comment]
Possible we need to increase the grace period

```
    deployment.mixin.spec.template.spec.withTerminationGracePeriodSeconds(4800)

```

**Comment by kolesnikovae** [comment]
Termination grace period added in grafana/phlare#837. Closing for now
