### ISSUE TITLE
SelectMerge latency is high

### ISSUE THREAD

**Issue by kolesnikovae** [grafana/phlare#689]
Most of the queries spend significant time after all the samples were fetched and deduplicated. We need to figure out and fix what causes the latency.

For example, phlare-querier **SelectMergeStacktraces**:
![image](https://github.com/grafana/phlare/assets/12090599/947dd28f-7cb6-4c8c-8e17-9f296b0e2d4b)

Solving the problem may result in a very significant decrease in the overall query latencies (up to 50%).

It’s very likely that this is caused by pulling and merging resolved stacks from the ingesters: the size of the payload may be quite big. If this is the case, we may want to find a way to reduce it, e.g. by stack truncation:
![image](https://github.com/grafana/phlare/assets/12090599/2d8f252d-fdd0-4133-8e17-4866b6c1a8a5)

We may want to optimize the representation of results in this API: notice that stacks take appx. 50MB (encoded in protobuf). We should consider building a truncated tree (w/o insignificant nodes) as close to the storage as possible, instead of passing an array of stack traces along the way. That would also decrease CPU time of the query execution, and allocations as well:
<img width="1689" alt="image" src="https://github.com/grafana/phlare/assets/12090599/04f4b21e-f8e0-44d6-ab39-84d789932fd8">
![image](https://github.com/grafana/phlare/assets/12090599/785d2009-1357-44ff-a856-77fb7f6b56aa)

**Comment by kolesnikovae** [comment]
Also related: https://github.com/grafana/pyroscope/issues/2107

**Comment by cyriltovena** [comment]
Based on our discussions I think this is a great idea to use an opaque format for the internal API. We should use the Pyroscope tree package https://github.com/grafana/pyroscope/blob/254c5759900d3a2da6e6dfaf4ef2767c05cb45bb/pkg/storage/tree/tree.go between query-frontend - querier - ingester and store-gateway.

**Comment by kolesnikovae** [comment]
grafana/phlare#702 reduces the query duration 2-3 times in certain cases:

![Image](https://github.com/grafana/phlare/assets/12090599/c2b777fa-454a-49cc-92bf-67ed15337551)

As a bonus, resource consumption also decreased:

![Image](https://github.com/grafana/phlare/assets/12090599/c971290d-1dbb-442a-be0c-b945aef55a5d)

Closing the issue for now
