### ISSUE TITLE
Improve Locations in memory representation

### ISSUE THREAD

**Issue by cyriltovena** [grafana/phlare#797]
Same as https://github.com/grafana/phlare/pull/796 we can have reduce memory usage drastically if we have a better representation in memory that is irrespective of the file format.

The same  inefficient format is also used when opening a block and cache in memory.

<img width="2461" alt="image" src="https://github.com/grafana/phlare/assets/1053421/ba13d542-82ba-4bc0-9021-bf847a30ad29">

**Comment by kolesnikovae** [comment]
Resolved via #814
